<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>kt</string>
      <string>kts</string>
    </array>
    <key>foldingStartMarker</key>
    <string>(\{\s*(//.*)?$|^\s*// \{\{\{)</string>
    <key>foldingStopMarker</key>
    <string>^\s*(\}|// \}\}\}$)</string>
    <key>name</key>
    <string>Kotlin</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.kotlin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.package.kotlin</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s*(package)\b(?:\s*([^ ;$]+)\s*)?</string>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.import.kotlin</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.import.java</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.other.kotlin</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.type</string>
          </dict>
        </dict>
        <key>match</key>
        <string>^\s*(import)\s+([^ $.]+(?:\.(?:[`][^$`]+[`]|[^` $.]+))+)(?:\s+(as)\s+([`][^$`]+[`]|[^` $.]+))?</string>
        <key>name</key>
        <string>meta.import.kotlin</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#code</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>annotations</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(@[^ (]+)(\()?</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.annotation.kotlin</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.annotation-arguments.begin.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\)|\s|$)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.annotation-arguments.end.kotlin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.declaration.annotation.kotlin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>constant.other.key.kotlin</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.operator.assignment.kotlin</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>(\w*)\s*(=)</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
              <dict>
                <key>match</key>
                <string>,</string>
                <key>name</key>
                <string>punctuation.seperator.property.kotlin</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>@\w*</string>
            <key>name</key>
            <string>storage.type.annotation.kotlin</string>
          </dict>
        </array>
      </dict>
      <key>builtin-functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(apply|also|let|takeIf|run|takeUnless|with|print|println)\b\s*(?={|\()</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.kotlin</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(mutableListOf|listOf|mutableMapOf|mapOf|mutableSetOf|setOf)\b\s*(?={|\()</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.kotlin</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.kotlin</string>
              </dict>
            </dict>
            <key>match</key>
            <string>/\*\*/</string>
            <key>name</key>
            <string>comment.block.empty.kotlin</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments-inline</string>
          </dict>
        </array>
      </dict>
      <key>comments-inline</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.kotlin</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.line.double-slash.kotlin</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.kotlin</string>
              </dict>
            </dict>
            <key>match</key>
            <string>\s*((//).*$\n?)</string>
          </dict>
        </array>
      </dict>
      <key>class-literal</key>
      <dict>
        <key>begin</key>
        <string>(?=\b(?:class|interface|object)\s+\w+)\b</string>
        <key>end</key>
        <string>(?=\}|$)</string>
        <key>name</key>
        <string>meta.class.kotlin</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#keyword-literal</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(class|object|interface)\b\s+(\w+)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.modifier.kotlin</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.class.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\{|\(|:|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#keyword-literal</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#annotations</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(:)\s*(\w+)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.declaration.kotlin</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.other.inherited-class.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?={|=|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#braces</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parens</string>
          </dict>
        </array>
      </dict>
      <key>literal-functions</key>
      <dict>
        <key>begin</key>
        <string>(?=\b(?:fun)\b)</string>
        <key>end</key>
        <string>(?=$|=|\})</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(fun)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\()</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>captures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.function.kotlin</string>
                  </dict>
                </dict>
                <key>match</key>
                <string>([\.&lt;\?&gt;\w]+\.)?(\w+|(`[^`]*`))</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.declaration.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?={|=|$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#braces</string>
          </dict>
        </array>
      </dict>
      <key>parameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.declaration.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=,|=|\))</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\w+(?=:)</string>
            <key>name</key>
            <string>variable.parameter.function.kotlin</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword-literal</string>
          </dict>
        </array>
      </dict>
      <key>keyword-literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\!in|\!is|as\?)</string>
            <key>name</key>
            <string>keyword.operator.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(in|is|as|assert)\b</string>
            <key>name</key>
            <string>keyword.operator.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(const)\b</string>
            <key>name</key>
            <string>storage.modifier.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(val|var)\b</string>
            <key>name</key>
            <string>storage.type.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(\_)\b</string>
            <key>name</key>
            <string>punctuation.definition.variable.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(data|inline|tailrec|operator|infix|typealias|reified)\b</string>
            <key>name</key>
            <string>storage.type.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(external|public|private|protected|internal|abstract|final|sealed|enum|open|annotation|override|vararg|typealias|expect|actual|suspend|yield|out|in)\b</string>
            <key>name</key>
            <string>storage.modifier.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(try|catch|finally|throw)\b</string>
            <key>name</key>
            <string>keyword.control.catch-exception.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(if|else|when)\b</string>
            <key>name</key>
            <string>keyword.control.conditional.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(while|for|do|return|break|continue)\b</string>
            <key>name</key>
            <string>keyword.control.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(constructor|init)\b</string>
            <key>name</key>
            <string>entity.name.function.constructor</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(companion|object)\b</string>
            <key>name</key>
            <string>storage.type.kotlin</string>
          </dict>
        </array>
      </dict>
      <key>keyword-operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(and|or|not|inv)\b</string>
            <key>name</key>
            <string>keyword.operator.bitwise.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(==|!=|===|!==|&lt;=|&gt;=|&lt;|&gt;)</string>
            <key>name</key>
            <string>keyword.operator.comparison.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(=)</string>
            <key>name</key>
            <string>keyword.operator.assignment.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(:(?!:))</string>
            <key>name</key>
            <string>keyword.operator.declaration.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\?:)</string>
            <key>name</key>
            <string>keyword.operator.elvis.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\-\-|\+\+)</string>
            <key>name</key>
            <string>keyword.operator.increment-decrement.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\-|\+|\*|\/|%)</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\+\=|\-\=|\*\=|\/\=)</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.assign.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\!|\&amp;\&amp;|\|\|)</string>
            <key>name</key>
            <string>keyword.operator.logical.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\.\.)</string>
            <key>name</key>
            <string>keyword.operator.range.kotlin</string>
          </dict>
        </array>
      </dict>
      <key>keyword-punctuation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(::)</string>
            <key>name</key>
            <string>punctuation.accessor.reference.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\?\.)</string>
            <key>name</key>
            <string>punctuation.accessor.dot.safe.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\.)</string>
            <key>name</key>
            <string>punctuation.accessor.dot.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\,)</string>
            <key>name</key>
            <string>punctuation.seperator.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\;)</string>
            <key>name</key>
            <string>punctuation.terminator.kotlin</string>
          </dict>
        </array>
      </dict>
      <key>keyword-constant</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(true|false|null|class)\b</string>
            <key>name</key>
            <string>constant.language.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(this|super)\b</string>
            <key>name</key>
            <string>variable.language.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0(x|X)[0-9A-Fa-f_]*)[L]?\b</string>
            <key>name</key>
            <string>constant.numeric.hex.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0(b|B)[0-1_]*)[L]?\b</string>
            <key>name</key>
            <string>constant.numeric.binary.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9][0-9_]*\.[0-9][0-9_]*[fFL]?)\b</string>
            <key>name</key>
            <string>constant.numeric.float.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9][0-9_]*[fFL]?)\b</string>
            <key>name</key>
            <string>constant.numeric.integer.kotlin</string>
          </dict>
        </array>
      </dict>
      <key>literal-string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.kotlin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.kotlin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-content</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>literal-raw-string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>"""</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"""</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.kotlin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.triple.kotlin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-content</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string-content</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.newline.kotlin</string>
            <key>match</key>
            <string>\\\s*\n</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.character.escape.kotlin</string>
            <key>match</key>
            <string>\\(x[\da-fA-F]{2}|u[\da-fA-F]{4}|.)</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\$)(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.keyword.kotlin</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.end.kotlin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>entity.string.template.element.kotlin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(Nothing|Any|Unit|String|CharSequence|Int|Boolean|Char|Long|Double|Float|Short|Byte|Array|List|Map|Set|dynamic)\b(\?)?</string>
            <key>name</key>
            <string>support.class.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(IntArray|BooleanArray|CharArray|LongArray|DoubleArray|FloatArray|ShortArray|ByteArray)\b(\?)?</string>
            <key>name</key>
            <string>support.class.kotlin</string>
          </dict>
          <dict>
            <key>match</key>
            <string>((?:[a-zA-Z]\w*\.)*[A-Z]+\w*[a-z]+\w*)(\?)</string>
            <key>name</key>
            <string>entity.name.type.class.kotlin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#keyword-punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?:[a-z]\w*(\.))*[A-Z]+\w*\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.dereference.kotlin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>entity.name.type.class.kotlin</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.group.begin.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.group.end.kotlin</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword-punctuation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword-operator</string>
          </dict>
        </array>
      </dict>
      <key>parens</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.group.begin.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.group.end.kotlin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.group.kotlin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#keyword-punctuation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#parameters</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>braces</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.group.begin.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.group.end.kotlin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.block.kotlin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>brackets</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\[</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.brackets.begin.kotlin</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\]</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.brackets.end.kotlin</string>
              </dict>
            </dict>
            <key>name</key>
            <string>meta.brackets.kotlin</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>code</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments-inline</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#annotations</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#class-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#braces</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#brackets</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword-operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword-constant</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword-punctuation</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#builtin-functions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-functions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#builtin-classes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-raw-string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal-string</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.kotlin</string>
    <key>uuid</key>
    <string>d9380650-5edc-447d-8dbd-98838c7d0adf</string>
  </dict>
</plist>